services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.5-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
